### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced-repo-mongo#13]
@mateodelnorte would you be interested in allowing the Promise support of the underlying Mongo library to bubble through to the `Repository` API? For example, allowing `Repository.get` to return a Promise if the callback is omitted? If so, maybe we could sync up sometime to chat about how I could help?

Thanks in advance.

**Comment by mateodelnorte** [comment]
Could you instead use something like http://bluebirdjs.com/docs/api/promise.promisify.html to wrap my code and return a promise? That way the concern of using promises is in the implementer's library and doesn't enforce a concern on sourced-repo-mongo.
