### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced-repo-mongo#15]
Hi Matt.

Just wondering if you have a feeling for how performant sourced and mongo is? I'm just getting to the point of integration tests, and a simple "create" test is taking in the order of 250 ms. I'm only doing one commit before the test and then another commit during the test.

**Comment by mateodelnorte** [comment]
That depends very much on the size of your objects. You can turn on the
debug statements for the modules with the DEBUG environment variable.

Typically, of there are performance problems committing, they can be
sidestepped by implementing a custom `serialize` function. The default is a
lodash implementation which is known to be very slow for Maps, Sets, and
some other built in classes.

**Comment by mateodelnorte** [comment]
Sorry, early morning comment. I meant overriding the default `snapshot` method. Something like the following could give you a big speedup: 
```

Blotter.prototype.snapshot = function snapshot () {
  return {
    id: this.id,
    items: this.items.toJson(),
    snapshotVersion: this.version,
    timestamp: this.timestamp,
    version: this.version
  };
};
```
where the above structure reflects the serialized structure of your entity. 

Can you tell where you are seeing performance bottlenecks?

**Comment by eddieajau** [comment]
> Can you tell where you are seeing performance bottlenecks?

Yes. The good news is it's not in sourced. It appears to be `self.events.insert` so the bottleneck is in the Node.js MongoDB driver. I'm running the latest official Docker image for Mongo. I'll try running up Mongo on local metal and see if there's a difference.

I have read, albeit in very old posts, that the official Node.js driver for Mongo is notoriously slow, and that Mongoose provides better performance.

**Comment by eddieajau** [comment]
Ok so Mongo on metal seems to be a little more performant but what I think I'm seeing is just a lot of overhead on the initial write and it looks like Mongo is setting up some indexes when you write your first record to the db. The subsequent `repo.get` calls are very fast.

**Comment by mateodelnorte** [comment]
Great. Thanks
