### ISSUE TITLE
Method to see if repository id exists without loading history.

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced-repo-mongo#16]
Hi Matt (and sorry for all these questions).

Would it be worth adding a `has` method to the `Repository` interface so that I can check whether an id exists without having to construct the entity? For example, before I do an `update` event to an entity, I want to check that the id exists first. So I can do a `get` but that seems like overkill when all I really need to know is has the object been created.

What are your thoughts?

**Comment by eddieajau** [comment]
Never mind. You do have to load the existing state of the entity first anyway before you update.

**Comment by mateodelnorte** [comment]
You should be able to do this with a regular mongo query. findOne will return the first event matching a given _id, which will ensure that you have an entity by that _id.
