### ISSUE TITLE
What's the point of this line?

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/sourced-repo-mongo#18]
https://github.com/mateodelnorte/sourced-repo-mongo/blob/master/index.js#L85

Just curious if I'm missing the point or not. I don't see any promises being pushed onto the array, but rather an event is being emitting.

**Comment by mateodelnorte** [comment]
It's not needed. Looks like a leftover from https://github.com/mateodelnorte/sourced-repo-mongo/commit/93596e38feb33ca9bebcfc9e20e1a07a88632c3b.

**Comment by mateodelnorte** [comment]
Fixed in version 0.3.12
