### ISSUE TITLE
different events with same Version

### ISSUE THREAD

**Issue by stephanknull** [mateodelnorte/sourced-repo-mongo#25]
Inspecting an error in our application i found out, that in our `Entity.events`-Collection were several events with same id & version.
It turned out that several simultaneous backend requests manipulating the same entity caused this. At the time of the request, version `x` existed and on this version the operation was executed. This led to an event with version `x+1` in all of these requests. 
According to my understanding this is not good, but it does not yet lead to data loss. The replay works fine.

If the new version now leads to the creation of a snapshot, we unfortunately lose data. Since several events exist with the same version, several snapshots are also created with the same version. Of course, each snapshot has only processed its own event. In replay, however, only one of the snapshots is used as the basis for replay.

I wasn't sure, If i should report it in `sourced` or here. But since I think it can be solved with a simple [unique index](https://docs.mongodb.com/manual/core/index-unique/#unique-compound-index) (on `{id, version}`), I post it here.
Please let me know, if you need some demonstration-code.

**Comment by mateodelnorte** [comment]
Hi there. This is an architectural problem. If you're running a single instance of your service, you'll want to use https://github.com/mateodelnorte/sourced-queued-repo to ensure a single entity cannot be accessed more than once, concurrently. If you're running multiple processes, you'll likely want to shard your instances so they each handle a subset of the available ids. 

*Note sourced-queued-repo currently does not have getAll and commitAll implemented.

**Comment by mateodelnorte** [comment]
You should be able to export a repo from a file with code similar to just these lines: https://github.com/mateodelnorte/sourced-queued-repo/blob/master/test/index.js#L55-L62. If you're running a single process, I'll bet that solves your issue.

**Comment by mateodelnorte** [comment]
Closing issue for now. Feel free to reopen if there are any items you think are working making a fix for. Thx.
