### ISSUE TITLE
Mongo db snapshots collection not has records

### ISSUE THREAD

**Issue by ssdulawat** [mateodelnorte/sourced-repo-mongo#4]
I create my entity as same as you describe in your example, but when I commit my entity it creates records in events, but not in snapshots collection.

**UserList Entity**
```javascript
var Entity = require('sourced').Entity;
var EventEmitter = require('events').EventEmitter;
var util = require('util');
function UserList () {
  Entity.call(this,arguments);
}
util.inherits(UserList, Entity);

UserList.prototype.init = function(param) {
    this.id = param.id;
	this.username=param.username;
	this.email=param.email;
	this.fullname=param.fullname;
	this.age=param.age;
	this.location=param.location;
	this.gender=param.gender;
	this.digest('init', param);
	this.emit('initialized', param, this);
};

module.exports.UserList = UserList;
```
**Commit Entity**
```javascript
router.post("/create",function(reg,res){
	var id = Date.now();
    var user = new UserList();

    user.init({ id: id ,username:"asda@gmail.com",email:"asd@gmail.com",fullname:"ASD Name",age:27,location:"World",gender:"Male"});
    repository.commit(user, function (err) {
      if (err) throw err;
      repository.get(id, function (err, u) {
        if (err) throw err;
		console.log(u);
		res.json(u);
      });
    });
});
```
What is wrong with my code?
When I use your example entity `Market` it works for me.

**Comment by ssdulawat** [comment]
I got reason what its not creating records in snapshots.

**Comment by mateodelnorte** [comment]
Glad you got it. ;) Guess you just hadn't saved more than the minimum snapshot frequency. 

One thing I'll point out: You're calling `this.emit('event_name', event)` at the end of your initialize function. You _probably_ want to call this.enqueue() instead. this.emit() will fire off the event immediately. this.enqueue() will wait to fire off the events until after the events and snapshots have been committed to mongo.
