### ISSUE TITLE
Get all records when I don't have ids

### ISSUE THREAD

**Issue by ssdulawat** [mateodelnorte/sourced-repo-mongo#5]
I'm trying to get all records using Repository but there only two method get and getAll, and Both method are required Id to get records. 
In my case I do not have any ids when my page is load first time. 
Can you please suggest me how I can get all records?

**Comment by mateodelnorte** [comment]
getAll doesn't require ids. if you pass an array of ids, it will get all the entities matching those ids. if you don't pass an array and just pass a function, it will first get the distinct set of ids for that entity type, then get all of them.
