### ISSUE TITLE
TypeError: Cannot read property 'forceShaptshot' of undefined on commit, but commit is successful

### ISSUE THREAD

**Issue by pcopley** [mateodelnorte/sourced-repo-mongo#70]
Posting issue here as it doesn't look like I can submit issues to [the up-to-date repo](https://github.com/CloudNativeEntrepreneur/sourced-repo-mongo) (cc @patrickleet ?)

I have an HTTP method I am calling via Azure functions (I think this is irrelevant but including for completeness). I am instantiating an object `Bill` and initializing it, then saving to MongoDB. This all works, however I get the following error calling `commit()`:

```
System.Private.CoreLib: Exception while executing function: Functions.GetUnprocessedDocuments. System.Private.CoreLib: node exited with code 1
LanguageWorkerConsoleLog[error] Worker a963b383-0c1f-445b-b773-3e8e24385993 uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): TypeError: Cannot read property 'forceSnapshot' of undefined     
at Repository._commitSnapshots (C:\src\personal\legislation\node_modules\sourced-repo-mongo\index.js:209:15)     
at _afterCommitEvents (C:\src\personal\legislation\node_modules\sourced-repo-mongo\index.js:59:10)     
at C:\src\personal\legislation\node_modules\sourced-repo-mongo\index.js:171:12     
at C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\utils.js:704:5     
at executeCallback (C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\operations\execute_operation.js:65:7)     
at C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\operations\insert_many.js:39:7     
at C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\operations\bulk_write.js:74:7     
at C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\utils.js:390:17     
at executeCallback (C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\utils.js:382:9)     
at handleCallback 
(C:\src\personal\legislation\node_modules\sourced-repo-mongo\node_modules\mongodb\lib\utils.js:109:55).
```

I've created [a gist that reproduces the issue](https://gist.github.com/pcopley/5199f136b957a1d7087993d6760dd60f) but it might be as simple as answering this question: is there a way I can disable snapshots entirely? These entities are all going to be extremely small, with at most a dozen or two very simple events. I am publishing messages on updates so other services are storing current state for UI, so I am basically already getting distributed snapshots in the places where I'll need them. However, these exceptions are messing up the HTTP calls because it makes Azure return a 500 on the request. I'll rather not just wrap in a `try` and swallow the exception though.

Any insights into what I am doing wrong or how I can fix this error would be greatly appreciated!

**Comment by patrickleet** [comment]
try using older major versions of sourced and let me know if one of those works.

I don't use this repo anymore and don't have time to maintain it

I have been using https://github.com/CloudNativeEntrepreneur/sourced-repo-typeorm with PSQL

It was moved to the other org because CI broke here and I did not have permissions to fix it.

**Comment by pcopley** [comment]
Thanks so much for replying Patrick. I will drop back a version or two and
let you know. I’ll also give TypeORM a try, it looks like it supports mongo
pretty easily also!

**Comment by patrickleet** [comment]
> I’ll also give TypeORM a try

it can but won't as is - most likely will need a PR for that to work, but yea should be possible.

FWIW, I use PSQL because the PSQL operator for kube is nice, and handles backups/restores for me.

**Comment by patrickleet** [comment]
if older versions of sourced work (probably 2?), then the shortest path is probably fixing the mongo repo implementation

**Comment by patrickleet** [comment]
fwiw, someone else also made this version forked from this repo:
https://github.com/pdmlab/sourced-repo-mongo-ts 

but I haven't tried it

**Comment by pcopley** [comment]
@patrickleet You've gone above and beyond with all the info, thanks. Actually, this project is so new I wasn't locked in to Mongo for this particular implementation - I was able to just spin up a Postgres node and use that instead and it looks like everything is working as expected, I get all the events persisted with no exceptions.

Are you accepting PRs on https://github.com/CloudNativeEntrepreneur/sourced-repo-typeorm to add Mongo support to the TypeORM implementation?

**Comment by patrickleet** [comment]
I would accept a PR for sure - I only had the immediate need for psql, but wanted to be able to support others down the line, and TypeORM as the base should allow for that - it does look like the mongo support is much more different than say mysql though, so I don't have a good grasp on level of effort for mongo, where mysql for example, is using json instead of jsonb basically.

**Comment by patrickleet** [comment]
also, for development, you can see a full working example cqrs/es system here: 
https://github.com/CloudNativeEntrepreneur/web3auth-meta 

Including setting up PSQL dbs, auth, granular permissions - uses a local kubernetes cluster
