### ISSUE TITLE
Create Order in Market after it has been loaded from repo

### ISSUE THREAD

**Issue by AlexZeitler** [mateodelnorte/sourced-repo-mongo#9]
WRT the test cases:
How do I call ```createOrder``` of a ```Market``` that has been loaded from the repository?

A call results in:
```EntityError: method 'market.createOrder' does not exist on model 'Market'```

**Comment by mateodelnorte** [comment]
Can you share the code you're using. You should just be able to call your method.

**Comment by AlexZeitler** [comment]
Thanks for your reply.
I fixed it but I'm not sure how. Will try to reproduce the error and post it here.
I'm closing the issues until then.
